/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BrazoRobotico;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSlider;
import rojerusan.RSButtonMetro;
import rojerusan.RSMetroTextPlaceHolder;

/**
 *
 * @author salat
 */
public class Interfaz extends javax.swing.JFrame {

    private int BASE = 1;
    private int BRAZODERECHO = 2;
    private int BRAZOIZQUIERDO = 3;
    private int PINZA = 4;

    MultiServo conexion = new MultiServo("COM3");

    public Interfaz() {
        this.themes();
        initComponents();
        this.inicializarSiders();

        this.setVisible(true);
        this.setTitle("Interfaz Configuración Arduino");

    }

    private void inicializarSiders() {
        this.sliderServoBase.setValue(90);
        this.displayServoBase.setText(String.valueOf(this.sliderServoBase.getValue()));
        this.sliderServoBD.setValue(80);
        this.displayServoBD.setText(String.valueOf(this.sliderServoBD.getValue()));
        this.sliderServoBI.setValue(90);
        this.displayServoBI.setText(String.valueOf(this.sliderServoBI.getValue()));
        this.sliderServoPinzas.setValue(10);
        this.displayServoPinza.setText(String.valueOf(this.sliderServoPinzas.getValue()));
    }

    private void themes() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            System.out.println("Error " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        displayServoBase = new javax.swing.JLabel();
        sliderServoBase = new javax.swing.JSlider();
        jPanel4 = new javax.swing.JPanel();
        displayServoBD = new javax.swing.JLabel();
        sliderServoBD = new javax.swing.JSlider();
        jPanel5 = new javax.swing.JPanel();
        displayServoBI = new javax.swing.JLabel();
        sliderServoBI = new javax.swing.JSlider();
        jPanel6 = new javax.swing.JPanel();
        displayServoPinza = new javax.swing.JLabel();
        sliderServoPinzas = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Servo Base", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 16))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayServoBase.setFont(new java.awt.Font("Century Gothic", 3, 25)); // NOI18N
        displayServoBase.setText("180°");
        jPanel3.add(displayServoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        sliderServoBase.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sliderServoBase.setMaximum(180);
        sliderServoBase.setPaintLabels(true);
        sliderServoBase.setPaintTicks(true);
        sliderServoBase.setSnapToTicks(true);
        sliderServoBase.setValue(180);
        sliderServoBase.setOpaque(false);
        sliderServoBase.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderServoBaseStateChanged(evt);
            }
        });
        jPanel3.add(sliderServoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 690, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 710, 110));

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Servo Brazo Derecho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 16))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayServoBD.setFont(new java.awt.Font("Century Gothic", 3, 25)); // NOI18N
        displayServoBD.setText("180°");
        jPanel4.add(displayServoBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        sliderServoBD.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sliderServoBD.setMaximum(180);
        sliderServoBD.setPaintLabels(true);
        sliderServoBD.setPaintTicks(true);
        sliderServoBD.setSnapToTicks(true);
        sliderServoBD.setValue(180);
        sliderServoBD.setOpaque(false);
        sliderServoBD.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderServoBDStateChanged(evt);
            }
        });
        jPanel4.add(sliderServoBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 690, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 710, 110));

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Servo Brazo izquierdo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 16))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayServoBI.setFont(new java.awt.Font("Century Gothic", 3, 25)); // NOI18N
        displayServoBI.setText("180°");
        jPanel5.add(displayServoBI, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        sliderServoBI.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sliderServoBI.setMaximum(180);
        sliderServoBI.setPaintLabels(true);
        sliderServoBI.setPaintTicks(true);
        sliderServoBI.setSnapToTicks(true);
        sliderServoBI.setValue(180);
        sliderServoBI.setOpaque(false);
        sliderServoBI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderServoBIStateChanged(evt);
            }
        });
        jPanel5.add(sliderServoBI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 690, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 710, 110));

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Servo Pinzas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 16))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayServoPinza.setFont(new java.awt.Font("Century Gothic", 3, 25)); // NOI18N
        displayServoPinza.setText("180°");
        jPanel6.add(displayServoPinza, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        sliderServoPinzas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sliderServoPinzas.setMaximum(180);
        sliderServoPinzas.setPaintLabels(true);
        sliderServoPinzas.setPaintTicks(true);
        sliderServoPinzas.setSnapToTicks(true);
        sliderServoPinzas.setOpaque(false);
        sliderServoPinzas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderServoPinzasStateChanged(evt);
            }
        });
        jPanel6.add(sliderServoPinzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 690, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 710, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderServoBaseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderServoBaseStateChanged

        String val = String.valueOf(sliderServoBase.getValue());
        conexion.enviar(Map.rTres(sliderServoBase.getValue()));
        this.displayServoBase.setText(val);

        System.out.println("Servo1.getValue():=> " + val);
        System.out.println("Map.rTres:=> " + (Map.rTres(sliderServoBase.getValue())));

    }//GEN-LAST:event_sliderServoBaseStateChanged

    private void sliderServoBDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderServoBDStateChanged
        String val = String.valueOf(sliderServoBD.getValue());
        conexion.enviar(Map.rTres(sliderServoBD.getValue()) + 63);
        this.displayServoBD.setText(val);

        System.out.println("Servo1.getValue():=> " + val);
        System.out.println("Map.rTres:=> " + (Map.rTres(sliderServoBD.getValue()) + 63));

    }//GEN-LAST:event_sliderServoBDStateChanged

    private void sliderServoPinzasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderServoPinzasStateChanged
        String val = String.valueOf(sliderServoPinzas.getValue());
        conexion.enviar(Map.rTres(sliderServoPinzas.getValue()) + 189);
        this.displayServoPinza.setText(val);

        System.out.println("Servo1.getValue():=> " + val);
        System.out.println("Map.rTres:=> " + (Map.rTres(sliderServoPinzas.getValue()) + 189));

    }//GEN-LAST:event_sliderServoPinzasStateChanged

    private void sliderServoBIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderServoBIStateChanged
        String val = String.valueOf(sliderServoBI.getValue());
        conexion.enviar(Map.rTres(sliderServoBI.getValue()) + 126);
        this.displayServoBI.setText(val);

        System.out.println("Servo1.getValue():=> " + val);
        System.out.println("Map.rTres:=> " + (Map.rTres(sliderServoBI.getValue()) + 126));
    }//GEN-LAST:event_sliderServoBIStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displayServoBD;
    private javax.swing.JLabel displayServoBI;
    private javax.swing.JLabel displayServoBase;
    private javax.swing.JLabel displayServoPinza;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSlider sliderServoBD;
    private javax.swing.JSlider sliderServoBI;
    private javax.swing.JSlider sliderServoBase;
    private javax.swing.JSlider sliderServoPinzas;
    // End of variables declaration//GEN-END:variables
}
