/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BrazoRobotico;

import java.awt.BorderLayout;

/**
 *
 * @author alan_
 */
public class InterfazPersonzalizada extends javax.swing.JFrame {
    
    
    
    /**
     * Creates new form InterfazPersonzalizada
     */
    public InterfazPersonzalizada() {
        this.themes();
        initComponents();
        
        
        this.panelServoBase.setLayout(new BorderLayout());
        this.panelServoBrazoDerecho.setLayout(new BorderLayout());
        this.panelServoBrazoIzuierdo.setLayout(new BorderLayout());
        this.panelServoPinzas.setLayout(new BorderLayout());
        
        CurvedSlider gaugePanelServoBase = new CurvedSlider(main.BASE, 25, 180);
        CurvedSlider gaugePanelServoBrazoDerecho = new CurvedSlider(main.BRAZODERECHO, 25, 180);
        CurvedSlider gaugePanelServoBrazoIzuierdo = new CurvedSlider(main.BRAZOIZQUIERDO, 25, 180);
        CurvedSlider gaugePanelServoPinzas = new CurvedSlider(main.PINZA, 38, 180);
        
        this.panelServoBase.add(gaugePanelServoBase, BorderLayout.CENTER);
        this.panelServoBrazoDerecho.add(gaugePanelServoBrazoDerecho, BorderLayout.CENTER);
        this.panelServoBrazoIzuierdo.add(gaugePanelServoBrazoIzuierdo, BorderLayout.CENTER);
        this.panelServoPinzas.add(gaugePanelServoPinzas, BorderLayout.CENTER);
        setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
        this.setTitle("Interfaz Configuración Arduino");
    }
    
    private void themes() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            System.out.println("Error " + e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelServoBase = new javax.swing.JPanel();
        panelServoBrazoDerecho = new javax.swing.JPanel();
        panelServoBrazoIzuierdo = new javax.swing.JPanel();
        panelServoPinzas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelServoBase.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout panelServoBaseLayout = new javax.swing.GroupLayout(panelServoBase);
        panelServoBase.setLayout(panelServoBaseLayout);
        panelServoBaseLayout.setHorizontalGroup(
            panelServoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        panelServoBaseLayout.setVerticalGroup(
            panelServoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel1.add(panelServoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 310, 310));

        panelServoBrazoDerecho.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout panelServoBrazoDerechoLayout = new javax.swing.GroupLayout(panelServoBrazoDerecho);
        panelServoBrazoDerecho.setLayout(panelServoBrazoDerechoLayout);
        panelServoBrazoDerechoLayout.setHorizontalGroup(
            panelServoBrazoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        panelServoBrazoDerechoLayout.setVerticalGroup(
            panelServoBrazoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel1.add(panelServoBrazoDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 310, 310));

        panelServoBrazoIzuierdo.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout panelServoBrazoIzuierdoLayout = new javax.swing.GroupLayout(panelServoBrazoIzuierdo);
        panelServoBrazoIzuierdo.setLayout(panelServoBrazoIzuierdoLayout);
        panelServoBrazoIzuierdoLayout.setHorizontalGroup(
            panelServoBrazoIzuierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        panelServoBrazoIzuierdoLayout.setVerticalGroup(
            panelServoBrazoIzuierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel1.add(panelServoBrazoIzuierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 310, 310));

        panelServoPinzas.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout panelServoPinzasLayout = new javax.swing.GroupLayout(panelServoPinzas);
        panelServoPinzas.setLayout(panelServoPinzasLayout);
        panelServoPinzasLayout.setHorizontalGroup(
            panelServoPinzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        panelServoPinzasLayout.setVerticalGroup(
            panelServoPinzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel1.add(panelServoPinzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 130, 310, 310));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Servo Pinza");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 90, 310, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Servo Base");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 310, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Servo Brazo Derecho");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 310, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Servo Brazo Izquierdo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 310, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelServoBase;
    private javax.swing.JPanel panelServoBrazoDerecho;
    private javax.swing.JPanel panelServoBrazoIzuierdo;
    private javax.swing.JPanel panelServoPinzas;
    // End of variables declaration//GEN-END:variables
}
